spring:
  application:
    name: paynow-agent

  datasource:
    url: jdbc:sqlite:paynow.db
    driver-class-name: org.sqlite.JDBC

  jpa:
    hibernate:
      ddl-auto: none   # don?t let Hibernate manage schema
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.community.dialect.SQLiteDialect

  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql

app:
  rate-limit:
    per-second: 5
  security:
    api-key: dev-secret
